- name: Set zabbix server configurations
  ansible.builtin.template:
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    backup: true
    mode: "0644"
  notify:
    - zabbix-server restart
    - zabbix-agent restart

- name: Set Zabbix frontend configurations
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    backup: true
    mode: "0644"
  with_items:
    - src: templates/zabbix.conf.php.j2
      dst: /etc/zabbix/web/zabbix.conf.php
    - src: templates/000-default.conf.j2
      dst: /etc/apache2/sites-available/000-default.conf
  notify:
    - php-fpm-deb restart
    - apache2 restart
